- hosts: all
  roles:
    - role: geerlingguy.java
      become: yes
    - role: geerlingguy.jenkins
      jenkins_plugins: ['github-branch-source','timestamper','workflow-aggregator','locale','ec2','greenballs','ansible','blueocean','sonar']
      become: yes
    - role: terraform
      terraform_version: 0.12.3
      become: yes
    # - role: docker 
    #   become: yes
  
  tasks: 
    - name: install software-properties-common
      apt: 
        name: software-properties-common
        state: present
        update_cache: yes
        force_apt_get: yes
      become: yes

    - name:  add ansible repository
      apt_repository: 
        repo: ppa:ansible/ansible
        update_cache: yes
      become: yes

    - name: install ansible
      apt: 
        name: ansible
        state: present
        # update_cache: yes
        force_apt_get: yes
      become: yes

    - name: install Node.js
      apt: 
        name: nodejs
        state: present
        # update_cache: yes
        force_apt_get: yes
      become: yes

    - name: install pip
      apt: 
        name: python-pip
        state: present
        # update_cache: yes
        force_apt_get: yes
      become: yes

    - name: install pip3
      apt: 
        name: python3-pip
        state: present
        # update_cache: yes
        force_apt_get: yes
      become: yes

    - name: install python boto
      pip:
        name: boto
        state: present
        executable: pip
      become: yes