  variable "master_ami" {}
  variable "private_subnet_ids" {}
  variable "calendar_key" {}
  variable "calendar_key_name" {}
  variable "security_groups" {}
  variable "bastion_ip" {}
  variable "bastion_user" {}
  variable "bastion_private_key" {}
  variable "db_host_name" {}
  variable "db_password" {}