  variable "ubuntu_ami" {}
  variable "subnet_id" {}
  variable "jenkins_key_name" {}
  variable "jenkins_key" {}
  variable "public_subnets_cidr" {}
  variable "vpc_id" {}
  variable "nat_gateway_interface_id" {}
  variable "bastion_ip" {}
  variable "bastion_user" {}
  variable "bastion_private_key" {}
  variable "jenkins_address" {}