- hosts: tag_Name_Jenkins_Slave

  tasks: 
  # - name: install rails 5.2
  #   shell: 'gem install rails -v 5.2'
  #   async: 300
  #   poll: 0
  #   register: rails_waiter
  #   become: true
  #   # environment: 
  #   #   PATH: '/home/ubuntu/.rvm/rubies/ruby-2.5.1/bin:/home/ubuntu/.rvm/gems/ruby-2.5.1/bin:/home/ubuntu/.rvm/gems/ruby-2.5.1@global/bin:{{ ansible_env.PATH }}' 
  #   # gem: 
  #   #   name: rails
  #   #   version: '5.2'
  #   #   state: present
  #   #   user_install: no

  - name: instal gems by bundler
    # environment: 
    #   PATH: '/home/ubuntu/.rvm/rubies/ruby-2.5.1/bin:/home/ubuntu/.rvm/gems/ruby-2.5.1/bin:/home/ubuntu/.rvm/gems/ruby-2.5.1@global/bin:{{ ansible_env.PATH }}' 
    shell: bundle
    args:
      chdir: {{ calendar_project_root }} 

  - name: Enable passenger module
    file:
      src: /usr/share/nginx/modules-available/mod-http-passenger.load
      dest: /etc/nginx/modules-enabled/50-mod-http-passenger.conf
      state: link
    become: yes
    notify: restart nginx

  - name: configure passenger
    replace:
      path: /etc/nginx/conf.d/mod-http-passenger.conf
      regexp: 'passenger_ruby /usr/bin/passenger_free_ruby;' 
      replace: 'passenger_ruby /usr/bin/ruby;'
    become: yes
    notify: restart nginx

  - name: remove default nginx config from enabled sites
    file: 
      path: /etc/nginx/sites-enabled/default
      state: absent
    become: yes
    notify: restart nginx

  - name: copy Calendar nginx config
    template: 
      src: templates/calendar.conf.j2
      dest: /etc/nginx/sites-available/calendar.conf
    become: yes
    notify: yes

  - name: Make Symlink for calendar.conf in sites-enabled
    file: 
      src: /etc/nginx/sites-available/calendar.conf
      dest: /etc/nginx/sites-enabled/calendar.conf
      state: link
    become: yes
    notify: restart nginx

  - name: copy configure database file
    template: 
      src: templates/database.yml.j2 
      dest: {{ calendar_project_root }}config/database.yml
    notify: restart nginx

  - name: start nginx
    service: 
      name: nginx
      state: started
      enabled: yes
    become: yes

  - name: configure databases
    # environment: 
    #   PATH: '/home/ubuntu/.rvm/rubies/ruby-2.5.1/bin:/home/ubuntu/.rvm/gems/ruby-2.5.1/bin:/home/ubuntu/.rvm/gems/ruby-2.5.1@global/bin:{{ ansible_env.PATH }}' 
    shell: "RAILS_ENV={{ calendar_rails_env }} && rails assets:precompile"
    args:
      chdir: {{ calendar_project_root }} 
  
  - name: test using rspec
    shell: "bundle exec rspec"
    args:
      chdir: {{ calendar_project_root }}
  
  - meta: flush_handler

  - name: Check that you can connect (GET) to a page and it returns a status 200
    uri:
      url: https://7office.com.ua
      follow_redirects: none
      status_code: [200,302,301,403]
    register: answer

  handlers: 
  - name: restart nginx
    service:
      name: nginx
      state: restarted
    become: yes